### ISSUE TITLE
看不懂源码呀，这个项目怎么启动呢

### ISSUE THREAD

**Issue by ownwolf** [realworld666/JsonViewer#1]
看不懂源码呀，这个项目怎么启动呢，本人java开发，

**Comment by realworld666** [comment]
This is a C# application. Build with Visual Studio and run

**Comment by ownwolf** [comment]
private void JsonViewer_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F && e.Control)
            {
                MessageBox.Show("ctrl + f");
                ShowFind();
            }
--------------------------------------------
为什么ctrl+c 无法识别呢

**Comment by ownwolf** [comment]
private void JsonViewer_KeyDown(object sender, KeyEventArgs e)
        {
            //if (e.KeyCode == Keys.C && e.Control)-----ctrl +c
            if (e.KeyCode == Keys.C && e.Modifiers==Keys.Control){
            }
--------------------------
为什么ctrl+c 无法识别呢

**Comment by realworld666** [comment]
Please make a pull request if you want anything changing. I'm not actively working on this at the moment
